---
title: "pollen AF test"
author: "Meng"
date: "2024-05-23"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(data.table)
library(stringr)
data <- "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/pollen_competition/"
setwd("/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/pollen_competition/")
```


## MAF
```{r}
freq_cross <- read.table(paste0(data,"cross1_31c_pollen.vcf"))
colnames(freq_cross) <- c("chrom", "pos", "ref", "alt", "dad", "dad0", "dad1", "pollen", "pollen0", "pollen1")
freq_cross <- freq_cross %>% mutate(pollen_raf = pollen0 / (pollen0 + pollen1))
freq_cross <- freq_cross %>% mutate(pollen_maf = ifelse(pollen_raf <= 0.5, pollen_raf, 1 - pollen_raf)) 


p<-ggplot(freq_cross, aes(x=pollen_raf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y) 

p1 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("pollen 1 - RAF")+ labs(x="MAF", y="Proportion")+ theme(text = element_text(size = 10))  + expand_limits(x=1) + ylim(0,0.13)

p<-ggplot(freq_cross, aes(x=pollen_maf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y) 

p2 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("pollen 1 - MAF")+ labs(x="MAF", y="Proportion")+ theme(text = element_text(size = 10)) + expand_limits(x=0.5) + ylim(0,0.13)
p <- p1 + p2 + plot_layout(widths = c(2,1))
ggsave(p, filename = paste0(data, "pollen1_ref_maf.png"), device = "png", height = 3, width = 6, units = "in")
```

```{r}
freq_cross <- freq_cross %>% mutate(leaf_raf = dad0 / (dad0 + dad1))
freq_cross <- freq_cross %>% mutate(leaf_maf = ifelse(leaf_raf <= 0.5, leaf_raf, 1 - leaf_raf)) 

p<-ggplot(freq_cross, aes(x=leaf_raf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y) 

p3 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("leaf 1 - RAF")+ labs(x="MAF", y="Proportion")+ theme(text = element_text(size = 10))  + expand_limits(x=1) + ylim(0,0.13)

p<-ggplot(freq_cross, aes(x=leaf_maf)) + geom_histogram(binwidth=0.01) 
p_data <- ggplot_build(p)$data[[1]]
p_data$y_prop <- p_data$y/sum(p_data$y) 

p4 <- ggplot(p_data, aes(x=x, y=y_prop)) +
  geom_bar(stat="identity", width = 0.01, color="white")  + theme_classic() + ggtitle("leaf 1 - MAF")+ labs(x="MAF", y="Proportion")+ theme(text = element_text(size = 10)) + expand_limits(x=0.5) + ylim(0,0.13)

p <- p1 + p2 + p3 + p4 + plot_layout(ncol = 2, widths = c(2,1))
ggsave(p, filename = paste0(data, "leaf_pollen1_ref_maf.png"), device = "png", height = 5, width = 6, units = "in")
```


## test
```{r}
cross7 <- read.table(paste0(data,"cross7_58b_pollen.vcf"))
colnames(cross7) <- c("chrom", "pos", "ref", "alt", "dad", "dad0", "dad1", "pollen", "pollen0", "pollen1")
head(cross7)
cross7 <- cross7 %>% filter(str_starts(chrom, "A"))
cross7$chrom <- factor(cross7$chrom)
levels(cross7$chrom)
 
cross7 <- as.data.table(cross7)

fisher_test <- function(dad0, dad1, pollen0, pollen1) {
    values <- c(dad0, dad1, pollen0, pollen1)
    contingency_table <- matrix(values, nrow = 2, byrow = TRUE)
    test_result <- fisher.test(contingency_table)
    odds_ratio <- test_result$estimate
    p_value <- test_result$p.value
    return(list(odds_ratio = odds_ratio, p_value = p_value))
}

cross7[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross7)]

write.table(cross7, file=paste0(data, "cross7_fishertest.txt"), quote = F, row.names = F,sep = "\t")
cross7 <- read.table(paste0(data, "cross7.txt"), header = T)

cross7_A1 <- cross7 %>% filter(chrom == "A1")
cross7_A2 <- cross7 %>% filter(chrom == "A2")
cross7_A3 <- cross7 %>% filter(chrom == "A3")
cross7_A4 <- cross7 %>% filter(chrom == "A4")


cross7_A4[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross7_A4)]
cross7_A3[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross7_A3)]
cross7_A1[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross7_A1)]
cross7_A2[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross7_A2)]

```
 
```{r}
p1 <- ggplot(cross7_A3, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab("-log10(p)")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) 

p2 <- ggplot(cross7_A2, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab(" ")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) + ylim(0, 9)

p3 <- ggplot(cross7_A3, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab(" ")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) + ylim(0, 9)

p4 <- ggplot(cross7_A4, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab(" ")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) + ylim(0, 9)

p1 + p2 + p3 + p4 +plot_layout(nrow = 1)
```

```{r}
ggplot(cross7, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab("Position on chromosome (Mb)")+ylab("-log10(p)")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) 

summary(cross7_A2$p_value)
```
```{r}
ggplot(cross7_A4, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab(" ")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) + ylim(0, 9) + xlim(51.5,52.5)
```

cross5

```{r}
cross5 <- read.table(paste0(data,"cross5_35h_02g_pollen.vcf"))
colnames(cross5) <- c("chrom", "pos", "ref", "alt", "dad", "dad0", "dad1", "pollen", "pollen0", "pollen1")
head(cross7)
cross7 <- cross7 %>% filter(chrom != "X" & chrom != "Y")
cross7$chrom <- factor(cross7$chrom)
levels(cross7$chrom)
```

```{r}
cross5_A4 <- cross5 %>% filter(chrom == "A4")
cross5 <- as.data.table(cross5)
cross5_A1 <- cross5 %>% filter(chrom == "A1")
cross5_A2 <- cross5 %>% filter(chrom == "A2")
cross5_A3 <- cross5 %>% filter(chrom == "A3")


fisher_test <- function(dad0, dad1, pollen0, pollen1) {
    values <- c(dad0, dad1, pollen0, pollen1)
    contingency_table <- matrix(values, nrow = 2, byrow = TRUE)
    test_result <- fisher.test(contingency_table)
    odds_ratio <- test_result$estimate
    p_value <- test_result$p.value
    return(list(odds_ratio = odds_ratio, p_value = p_value))
}

cross5_A4[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross5_A4)]
cross5_A3[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross5_A3)]
cross5_A1[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross5_A1)]
cross5_A2[, c("odds_ratio", "p_value") := fisher_test(dad0, dad1, pollen0, pollen1), by = 1:nrow(cross5_A2)]

write.table(cross5_A4, file=paste0(data, "cross5_A4"), quote = F, row.names = F,sep = "\t")
write.table(cross5_A1, file=paste0(data, "cross5_A1"), quote = F, row.names = F,sep = "\t")
write.table(cross5_A2, file=paste0(data, "cross5_A2"), quote = F, row.names = F,sep = "\t")
write.table(cross5_A3, file=paste0(data, "cross5_A3"), quote = F, row.names = F,sep = "\t")

cross5_A4<- read.table(paste0(data, "cross5_A4"), header = T)
cross7 <- read.table(paste0(data, "cross7.txt"), header = T)
```

```{r}
p1 <- ggplot(cross5_A1, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab("-log10(p)")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) + ylim(0, 9)

p2 <- ggplot(cross5_A2, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab(" ")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) + ylim(0, 9)

p3 <- ggplot(cross5_A3, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab(" ")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) + ylim(0, 9)

p4 <- ggplot(cross5_A4, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ facet_grid(.~chrom,scales="free_x", switch = "x", space = "free_x") +  xlab(" ")+ylab(" ")+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 10)) + ylim(0, 9)

p1 + p2 + p3 + p4 +plot_layout(nrow = 1) 
```
```{r}
p1
```

## A4, Male10
```{r}
cross <- read.table(paste0(data,"cross10_15c_test_A4.tmp"))
colnames(cross) <- c("chrom", "pos", "p_value")
#cross <- cross %>% filter(p_value < 1)
cross <- cross %>% filter(pos/1000000>140)



p <- ggplot(cross, aes(x = pos/1000000, y = -log10(p_value)))+geom_point(size = 0.3, alpha=0.3)+ xlab("Position on chromosome (Mb)")+ylab("-log10(p value)")+ggtitle(paste0("Male ", 10))+theme_bw() + theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),panel.spacing = unit(0.1, "cm"),strip.background = element_blank(),strip.placement = "outside")+ theme(text = element_text(size = 11)) 

```

