---
title: "coverage"
author: "Meng"
date: "2025-07-08"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
data <- "/Users/yuanmeng/Library/CloudStorage/OneDrive-UniversityofToronto/Manuscripts/pollen_competition/"
```

## compare number of mapped reads on X/Y vs autosomes combined in pollen vs leaf 
Y vs A
```{r}
reads <- read.table(paste0(data, "read_counts.tsv"), header = T)
reads <- reads %>% mutate(A = rowSums(reads[,c(2,3,4,5)]))

# Y vs A
reads <- reads[c(11:20, 31:40), c(1,7,9)]

pollen <- reads[c(1:10),]
leaf <- reads[c(11:20),]
reads <- cbind(pollen, leaf)

reads <- reads[,c(1,2,3,5,6)]
reads <- reads %>% mutate(pollen_ratio = Y/A) %>% mutate(leaf_ratio = Y.1/A.1) %>% mutate(OR = Y * A.1 / (A * Y.1))
write.table(reads, file = paste0(data, "OR_YA.txt"), sep = "\t", row.names = F, quote = F)

result <- t(apply(reads, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

table <- matrix(unlist(reads[1,c(2:5)]), nrow = 2, byrow = TRUE)
chisq.test(table, correct = FALSE)
```

X vs A
```{r}
reads <- read.table(paste0(data, "read_counts.tsv"), header = T)
reads <- reads %>% mutate(A = rowSums(reads[,c(2,3,4,5)]))

reads <- reads[c(11:20, 31:40), c(1,8,9)]

pollen <- reads[c(1:10),]
leaf <- reads[c(11:20),]
reads <- cbind(pollen, leaf)

reads <- reads[,c(1,2,3,5,6)]
reads <- reads %>% mutate(pollen_ratio = X/A) %>% mutate(leaf_ratio = X.1/A.1) %>% mutate(OR = X * A.1 / (A * X.1))
write.table(reads, file = paste0(data, "OR_XA.txt"), sep = "\t", row.names = F, quote = F)

result <- t(apply(reads, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

table <- matrix(unlist(reads[5,c(2:5)]), nrow = 2, byrow = TRUE)
test <- chisq.test(table, correct = FALSE)
test$p.value
write.table(result, file = paste0(data, "pval_XA.txt"), sep = "\t", row.names = F, quote = F)
```


## compare read counts between X/Y to each autosome

OR
```{r}
reads <- read.table(paste0(data, "read_counts.tsv"), header = T)
pollen <- reads[c(11:20),c(1:5,7,8)]
leaf <- reads[c(31:40),c(1:5,7,8)]

# look at odds ratios first
pollen <- pollen %>% mutate(pollen_ratio_YA1 = Y/A1) %>% mutate(pollen_ratio_YA2 = Y/A2) %>% mutate(pollen_ratio_YA3 = Y/A3) %>% mutate(pollen_ratio_YA4 = Y/A4) %>% mutate(pollen_ratio_XA1 = X/A1) %>% mutate(pollen_ratio_XA2 = X/A2) %>% mutate(pollen_ratio_XA3 = X/A3) %>% mutate(pollen_ratio_XA4 = X/A4)

leaf <- leaf %>% mutate(leaf_ratio_YA1 = Y/A1) %>% mutate(leaf_ratio_YA2 = Y/A2) %>% mutate(leaf_ratio_YA3 = Y/A3) %>% mutate(leaf_ratio_YA4 = Y/A4) %>% mutate(leaf_ratio_XA1 = X/A1) %>% mutate(leaf_ratio_XA2 = X/A2) %>% mutate(leaf_ratio_XA3 = X/A3) %>% mutate(leaf_ratio_XA4 = X/A4)

reads <- cbind(pollen[,c(1,8:15)], leaf[,8:15])
colnames(reads)

reads <- reads %>% 
    mutate(OR_YA1 = pollen_ratio_YA1 / leaf_ratio_YA1) %>% 
    mutate(OR_YA2 = pollen_ratio_YA2 / leaf_ratio_YA2) %>% 
    mutate(OR_YA3 = pollen_ratio_YA3 / leaf_ratio_YA3) %>% 
    mutate(OR_YA4 = pollen_ratio_YA4 / leaf_ratio_YA4) %>% 
    mutate(OR_XA1 = pollen_ratio_XA1 / leaf_ratio_XA1) %>% 
    mutate(OR_XA2 = pollen_ratio_XA2 / leaf_ratio_XA2) %>% 
    mutate(OR_XA3 = pollen_ratio_XA3 / leaf_ratio_XA3) %>% 
    mutate(OR_XA4 = pollen_ratio_XA4 / leaf_ratio_XA4)
write.table(reads, file = paste0(data, "reads_OR_XYA.txt"), row.names = F, quote = F)
```

Y tests
```{r}
# contigency test
reads <- read.table(paste0(data, "read_counts.tsv"), header = T)
pollen <- reads[c(11:20),c(1:5,7,8)]
leaf <- reads[c(31:40),c(1:5,7,8)]

reads2 <- cbind(pollen[,c(1:7)], leaf[,c(2:7)])
colnames(reads2)[8:13] <- c("A1.1", "A2.1", "A3.1", "A4.1", "Y.1",  "X.1")
write.table(reads2, file = paste0(data, "reads2_tidy.txt"), row.names = F, quote = F)

# for Y
col <- as.data.frame(colnames(reads2))
reads_a1 <- reads2[,c(1,2,6,8,12)]
reads_a2 <- reads2[,c(1,3,6,9,12)]
reads_a3 <- reads2[,c(1,4,6,10,12)]
reads_a4 <- reads2[,c(1,5,6,11,12)]

# all p=0
result_a1 <- t(apply(reads_a1, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

result_a2 <- t(apply(reads_a2, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

result_a3 <- t(apply(reads_a3, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

result_a4 <- t(apply(reads_a4, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))
```


X tests 
```{r}
# for X
reads_a1 <- reads2[,c(1,2,7,8,13)]
reads_a2 <- reads2[,c(1,3,7,9,13)]
reads_a3 <- reads2[,c(1,4,7,10,13)]
reads_a4 <- reads2[,c(1,5,7,11,13)]

result_a1 <- t(apply(reads_a1, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

result_a2 <- t(apply(reads_a2, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

result_a3 <- t(apply(reads_a3, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

result_a4 <- t(apply(reads_a4, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))
write.table(result_a1, file = paste0(data, "pval_XA1.txt"), sep = "\t", row.names = F, quote = F)
write.table(result_a2, file = paste0(data, "pval_XA2.txt"), sep = "\t", row.names = F, quote = F)
write.table(result_a3, file = paste0(data, "pval_XA3.txt"), sep = "\t", row.names = F, quote = F)
write.table(result_a4, file = paste0(data, "pval_XA4.txt"), sep = "\t", row.names = F, quote = F)
```


## compare read counts between X and Y
```{r}
# look at odds ratios first
pollen <- pollen %>% mutate(pollen_ratio_XY = as.numeric(X)/as.numeric(Y)) 

leaf <- leaf %>% mutate(leaf_ratio_XY = as.numeric(X)/as.numeric(Y)) 

reads <- cbind(pollen[,c(1,8)], leaf[,8])
colnames(reads)[3] <- "leaf_ratio_XY"
reads <- reads %>% mutate(OR_XY = pollen_ratio_XY / leaf_ratio_XY)
write.table(reads, file = paste0(data, "reads_OR_XY.txt"), row.names = F, quote = F, sep = "\t")


# test
reads <- cbind(pollen[,c(1,6,7)], leaf[,c(6,7)])


result <- t(apply(reads, 1, function(row) {
  table <- matrix(as.numeric(row[2:5]), nrow = 2, byrow = TRUE)
  test <- chisq.test(table, correct = FALSE)
  c(sample = row[1], p_value = test$p.value)
}))

table <- matrix(unlist(reads[5,c(2:5)]), nrow = 2, byrow = TRUE)
chisq.test(table, correct = FALSE)
write.table(result, file = paste0(data, "pval_XY.txt"), sep = "\t", row.names = F, quote = F)

```

